### ISSUE TITLE
Malformed ciphertext files can cause `fread` with negative values upon decryption

### ISSUE THREAD

**Issue by defuse** [defuse/php-encryption#115]
I broke the encryption function, so it was generating bad ciphertexts. Then, when the test cases tried to decrypt them, this happened:

As you can see in the output, I added some echos and `$ciphertext_end` is 3 while `$pos` is 36.

```
Fatal error: Undefined class constant 'VERSION' in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 308

Call Stack:
    0.0002     243936   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/tests/stream/encrypt.php:0
    0.0018     426048   2. Defuse\Crypto\File::encryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/tests/stream/encrypt.php:25
    0.0019     427896   3. Defuse\Crypto\File::encryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:101

Decrypting
--------------------------------------------------

Load Key:
	0.00s (Memory: 306.12 KB)
C end: 3
36
PHP Warning:  fread(): Length parameter must be greater than 0 in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 560
PHP Stack trace:
PHP   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/tests/stream/decrypt.php:0
PHP   2. Defuse\Crypto\File::decryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/tests/stream/decrypt.php:25
PHP   3. Defuse\Crypto\File::decryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:172
PHP   4. fread() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:560

Warning: fread(): Length parameter must be greater than 0 in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 560

Call Stack:
    0.0001     243936   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/tests/stream/decrypt.php:0
    0.0017     426064   2. Defuse\Crypto\File::decryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/tests/stream/decrypt.php:25
    0.0017     428272   3. Defuse\Crypto\File::decryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:172
    0.0019     432056   4. fread() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:560
```

**Comment by defuse** [comment]
Before fixing this, create a test case that reproduces the problem.

**Comment by paragonie-scott** [comment]
Is this fixed in #116 or can you still trigger this condition?

**Comment by defuse** [comment]
I did not fix it. I tried to reproduce it and instead ended up with https://github.com/defuse/php-encryption/issues/131. I'll try to find a way to reproduce this specific issue.

**Comment by defuse** [comment]
Ok, here's how to reproduce it:

```
[firexware@firexware-pc php-encryption]$ ./test.sh  # run the tests to generate sample ciphertexts
...
[firexware@firexware-pc php-encryption]$ cat test.php 
<?php

require 'autoload.php';

echo "Creating a key...\n";
$key = \Defuse\Crypto\File::createNewRandomKey();

echo "Decrypting /tmp/bad.data...\n";
\Defuse\Crypto\File::decryptFile("/tmp/bad.data", "/tmp/bad.data.dec", $key);
echo "Done.\n";
[firexware@firexware-pc php-encryption]$ head -c 64 test/stream/wat-encrypted.data > /tmp/bad.data
[firexware@firexware-pc php-encryption]$ php test.php
Creating a key...
Decrypting /tmp/bad.data...
PHP Warning:  fread(): Length parameter must be greater than 0 in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 582
PHP Stack trace:
PHP   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:0
PHP   2. Defuse\Crypto\File::decryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:9
PHP   3. Defuse\Crypto\File::decryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:185
PHP   4. fread() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:582

Warning: fread(): Length parameter must be greater than 0 in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 582

Call Stack:
    0.0001     230432   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:0
    0.0021     452800   2. Defuse\Crypto\File::decryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:9
    0.0022     455712   3. Defuse\Crypto\File::decryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:185
    0.0024     458792   4. fread() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:582

PHP Fatal error:  Uncaught exception 'Defuse\Crypto\Exception\CannotPerformOperationException' with message 'Could not read input file during decryption' in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:587
Stack trace:
#0 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php(185): Defuse\Crypto\File::decryptResource(Resource id #11, Resource id #12, '\x83@\x13\x07\x0E\xA4\x94&\xBE\xF3\xDF\x89\xA9\xA7m...')
#1 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php(9): Defuse\Crypto\File::decryptFile('/tmp/bad.data', '/tmp/bad.data.d...', '\x83@\x13\x07\x0E\xA4\x94&\xBE\xF3\xDF\x89\xA9\xA7m...')
#2 {main}
  thrown in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 587

Fatal error: Uncaught exception 'Defuse\Crypto\Exception\CannotPerformOperationException' with message 'Could not read input file during decryption' in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 587

Defuse\Crypto\Exception\CannotPerformOperationException: Could not read input file during decryption in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 587

Call Stack:
    0.0001     230432   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:0
    0.0021     452800   2. Defuse\Crypto\File::decryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:9
    0.0022     455712   3. Defuse\Crypto\File::decryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:185
```

In the error message, you can see:

```
Warning: fread(): Length parameter must be greater than 0 in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 582
```

**Comment by defuse** [comment]
This is still a problem.

```
[firexware@firexware-pc php-encryption]$ php test.php 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/libsodium.so' - libsodium.so.13: cannot open shared object file: No such file or directory in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/libsodium.so' - libsodium.so.13: cannot open shared object file: No such file or directory in Unknown on line 0
Creating a key...
Decrypting /tmp/bad.data...
PHP Fatal error:  Uncaught exception 'RangeException' with message 'Tried to read less than 0 bytes' in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:776
Stack trace:
#0 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php(549): Defuse\Crypto\File::readBytes(Resource id #10, -20)
#1 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php(182): Defuse\Crypto\File::decryptResource(Resource id #10, Resource id #11, Object(Defuse\Crypto\Key))
#2 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php(9): Defuse\Crypto\File::decryptFile('/tmp/bad.data', '/tmp/bad.data.d...', Object(Defuse\Crypto\Key))
#3 {main}
  thrown in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 776

Fatal error: Uncaught exception 'RangeException' with message 'Tried to read less than 0 bytes' in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 776

RangeException: Tried to read less than 0 bytes in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 776

Call Stack:
    0.0001     230424   1. {main}() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:0
    0.0021     463056   2. Defuse\Crypto\File::decryptFile() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php:9
    0.0022     465904   3. Defuse\Crypto\File::decryptResource() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:182
    0.0030     509872   4. Defuse\Crypto\File::readBytes() /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:549
```

**Comment by defuse** [comment]
This explains it:

```
                if ($pos + $config->bufferByteSize() >= $cipher_end) {
                    $break = true;
                    echo "CIPHER END $cipher_end \n";
                    echo "POS $cipher_end \n";
                    $read = self::readBytes(
                        $inputHandle,
                        $cipher_end - $pos + 1
                    );
                    echo "ZZZZZZZZZ";
```

```
Creating a key...
Decrypting /tmp/bad.data...
CIPHER END 31 
POS 52 
PHP Fatal error:  Uncaught exception 'RangeException' with message 'Tried to read less than 0 bytes' in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php:779
Stack trace:
#0 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php(551): Defuse\Crypto\File::readBytes(Resource id #10, -20)
#1 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php(182): Defuse\Crypto\File::decryptResource(Resource id #10, Resource id #11, Object(Defuse\Crypto\Key))
#2 /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/test.php(9): Defuse\Crypto\File::decryptFile('/tmp/bad.data', '/tmp/bad.data.d...', Object(Defuse\Crypto\Key))
#3 {main}
  thrown in /home/firexware/Data-1/Documents/FireXware/Programming/gits/php-encryption/src/File.php on line 779
```

So it's a logic error in the way we're using ftell() and stuff. Let's just get rid of `ftell()` and do streaming-only stuff except for one rewind.

**Comment by defuse** [comment]
There's now a unit test for this added in #148.

**Comment by paragonie-scott** [comment]
When #148 + #170 are merged, this is fixed.

**Comment by defuse** [comment]
Done yay!
